version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info -PskipArm

test_script:
  - gradlew.bat check --info -PskipArm

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
